import java.util.*;
public class CollectionMethod{
	public static void main(String[] args) {
		//String data type
		String s1=new String("Dog");
		String s2=new String("Cat");
		System.out.println(s1.compareTo(s2));

		//wrapper class


		Double t1=16.07;
		Double t2=23.45;

		System.out.println(t1.compareTo(t2));


		Character p1='A';
		Character p2='A';
		System.out.println(p1.compareTo(p2));
	}
}



		