class Practice{
    public static void main(String[] args) {
       int num=10;
       int firstNum=0;
       int secondNum=1;
       System.out.println(firstNum);
       System.out.println(secondNum);

       for(int i=3;i<=num;i++){


       int sum=firstNum+secondNum;//
       System.out.println(sum);
       firstNum=secondNum;
       secondNum=sum;

       

        

       
   }
}
    }
       