class Practice {
    public static void main(String[] args) {
       int n=4;
       for(int i=1;i<=4;i++){
            for(int j=1;j<=n-i;j++){
                System.out.print(" ");
            }
                for(int star=1;star<=(2*i-1);star++){
                    System.out.print("*");
                }
                    System.out.println();
                }
                


        for(int i=n;i>=1;i--){
            for(int j=1;j<=n-i;j++){
                System.out.print(" ");
            }
                for(int star=1;star<=(2*i-1);star++){
                    System.out.print("*");
                }
                    System.out.println();
                
            

                
            
            
        
    }
    }
}



